### PR TITLE
Added generic tftp

### PR DESCRIPTION
**Pull request by ayeleta**
Assumes there is a tftp resource holding the  data and gets the data
from it

---

This change is [Reviewable](https://reviewable.io/reviews/qualisystemslab/awesome-sandbox/2)

### CODE REVIEW

**Comment by AlonSaggie** [comment]
Regarding the comment:
_raise QualiError(self.name, "Attribute: " + attribute_name + " not found")

consider changing to:
raise QualiError(self.name, "Attribute '" + attribute_name + "' not found " + "for resource '" + self.name +"'."_

In the QualiError, the first argument is the resource's name so I think there is some duplication in adding it to the message again.
The str of a QualiError will be
'CloudShell error at <ResourceX>. Error is:<Message>

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

_[EnvironmentCommands/SaveSnapshot.py, line 13 [r1]](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2#-KI6Sl6FnZoflpOIBWMO:-KI6Sl6FnZoflpOIBWMP:182069895) ([raw file](https://github.com/qualisystemslab/awesome-sandbox/blob/acbbbc47fd2411d7753b0de338328745e42ee907/EnvironmentCommands/SaveSnapshot.py#L13)):_

> ``` Python
> logger = get_qs_logger(log_category='EnvironmentCommands',
>                        log_group=reservation_id, log_file_prefix='SaveSnapshot')
> tftp = ResourceBase('TFTP Server')
> ```

+invalid 

Please change 'tftp' to 'tftp_server_resource'.

---

_[EnvironmentCommands/SaveSnapshot.py, line 14 [r1]](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2#-KI6SpS-XBXVRb-EhSVq:-KI6SpS-XBXVRb-EhSVr:-1253456781) ([raw file](https://github.com/qualisystemslab/awesome-sandbox/blob/acbbbc47fd2411d7753b0de338328745e42ee907/EnvironmentCommands/SaveSnapshot.py#L14)):_

> ``` Python
>                        log_group=reservation_id, log_file_prefix='SaveSnapshot')
> tftp = ResourceBase('TFTP Server')
> tftp_path =tftp.GetAttribute("TFTP path")
> ```

+invalid 

Please change 'tftp_path' to 'tftp_server_destination_path'

---

_[EnvironmentCommands/Setup.py, line 13 [r1]](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2#-KI6R9CP1-dmJBwiszs3:-KI6R9CP1-dmJBwiszs4:182069895) ([raw file](https://github.com/qualisystemslab/awesome-sandbox/blob/acbbbc47fd2411d7753b0de338328745e42ee907/EnvironmentCommands/Setup.py#L13)):_

> ``` Python
>                        log_group=reservation_id, log_file_prefix='Setup')
> 
> tftp = ResourceBase('TFTP Server')
> ```

+invalid 

Please change 'tftp' to 'tftp_server_resource'.

---

_[EnvironmentCommands/Setup.py, line 15 [r1]](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2#-KI6OuXAacImEpmQlHTd:-KI6OuXAacImEpmQlHTe:-1253456781) ([raw file](https://github.com/qualisystemslab/awesome-sandbox/blob/acbbbc47fd2411d7753b0de338328745e42ee907/EnvironmentCommands/Setup.py#L15)):_

> ``` Python
> tftp = ResourceBase('TFTP Server')
> tftp_path =tftp.GetAttribute("TFTP path")
> ```

+invalid 

Please change 'tftp_path' to 'tftp_server_destination_path'

---

_[EnvironmentCommands/Teardown.py, line 12 [r1]](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2#-KI6QFPqU-4alhttBPEm:-KI6QFPqU-4alhttBPEn:182069895) ([raw file](https://github.com/qualisystemslab/awesome-sandbox/blob/acbbbc47fd2411d7753b0de338328745e42ee907/EnvironmentCommands/Teardown.py#L12)):_

> ``` Python
> logger = get_qs_logger(log_category='EnvironmentCommands',
>                        log_group=reservation_id, log_file_prefix='Teardown')
> tftp = ResourceBase('TFTP Server')
> ```

+invalid 

Please change 'tftp' to 'tftp_server_resource'.

---

_[EnvironmentCommands/Teardown.py, line 13 [r1]](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2#-KI6QHbPmhBk1I_yPcEG:-KI6QHbPmhBk1I_yPcEH:62358013) ([raw file](https://github.com/qualisystemslab/awesome-sandbox/blob/acbbbc47fd2411d7753b0de338328745e42ee907/EnvironmentCommands/Teardown.py#L13)):_

> ``` Python
>                        log_group=reservation_id, log_file_prefix='Teardown')
> tftp = ResourceBase('TFTP Server')
> tftp_path =tftp.GetAttribute("TFTP path")
> ```

Please change 'tftp_path' to 'tftp_server_destination_path'

---

_[QualiEnvironmentUtils/Resource.py, line 37 [r1]](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2#-KI6Rt9ED6dE_AULqGWF:-KI6Rt9ED6dE_AULqGWG:-562996958) ([raw file](https://github.com/qualisystemslab/awesome-sandbox/blob/acbbbc47fd2411d7753b0de338328745e42ee907/QualiEnvironmentUtils/Resource.py#L37)):_

> ``` Python
>             if attribute.Name == attribute_name:
>                 return attribute.Value
>         raise QualiError(self.name, "Attribute: " + attribute_name + " not found")
> ```

+enhancement 

consider changing to:
raise QualiError(self.name, "Attribute '" + attribute_name + "' not found " + "for resource '" + self.name +"'."

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2)_

**Comment by AlonSaggie** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2)_

**Comment by AlonSaggie** [comment]
Hi @ayeleta,
Looks good.
Please fix the issues and perform another commit to the 'first-check-in' branch. Let me know once done and I'll merge the pull request.

**Comment by GregSloan** [comment]
So – I cloned the repo before these changes.  How do I get these changes into my fork?

Gregory Sloan  |  Sr. Field Solutions Engineer

Office: +1.408.588.1774 ext. 518
Mobile: +1.949.981.1356

[logo-for-email-sig2]

**Comment by AlonSaggie** [comment]
Reviewed 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystemslab/awesome-sandbox/2)_

**Pull request merged**
